### ISSUE TITLE
Error when registring a new user

### ISSUE THREAD

**Issue by Akodiat** [sulcgroup/oxdna-web#17]
A colleague tried to register today, but the page freezes at _processing_.

There is this error in the console:
`register:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onload (script.js:631)`

...which is caused by trying to call `const response = JSON.parse(request.response)` while `request.response` is an html error string:
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Does anyone have an idea what goes wrong?

**Comment by ErikPoppleton** [comment]
Issue was the character limit on the email field in the SQL table.  The length has been increased from 32 to 64 characters.
