### ISSUE TITLE
oxview help 

### ISSUE THREAD

**Issue by YJH-hi** [sulcgroup/oxdna-web#31]
Excuse me. How does the oxview make this type of diagram?
<img width="282" alt="联想截图_20241104112509" src="https://github.com/user-attachments/assets/9bc5b5c0-1bf7-4391-8a6e-01af523c6186">
I only could do this type of picture in oxview
<img width="966" alt="联想截图_20241104112715" src="https://github.com/user-attachments/assets/3d47484e-b6fa-4194-af1b-95b9b4d444f8">
Can you give me some way to do that?

**Comment by zoombya** [comment]
Hi, you are correct oxview is not able to visualize the structure in this way. 
To get the render you are after you need to export the configuration to PDB using [TacoOxDNA](http://tacoxdna.sissa.it/oxDNA_PDB). And than use [ChimeraX](https://www.cgl.ucsf.edu/chimerax/download.html) to render the image.
Additionally you might consider using the [oxView stand alone version](https://sulcgroup.github.io/oxdna-viewer/), which has a bit improved visuals over the legacy one provided as part of oxdna-web. 
Best !

**Comment by YJH-hi** [comment]
Excuse me.  Is the oxView stand alone version a separate software? Where can I download it? I found a web page as follows. Is it the oxView stand alone version?
<img width="1281" alt="联想截图_20241104165042" src="https://github.com/user-attachments/assets/e65edbde-e943-47b5-a123-4e8934a1221e">

**Comment by zoombya** [comment]
it's just a more updated and maintained version of the software you use in oxdna-web.
it's also available just online, like the version you use in oxdna-web.

**Comment by YJH-hi** [comment]
Do you have a rendering tutorial of ChimeraX? It's a protein visualisation software, but I don't know how to render nucleic acids. I can't find the instruction online.

**Comment by YJH-hi** [comment]
Excuse me, one more question: Which type of file  can be opened in the oxView? I download the last configuration and Topology file, but none of them can be opened in oxView

**Comment by zoombya** [comment]
Dear @YJH-hi, if you downloaded a topology and conf file you need to load both of them at the same time, for oxview to show smth. The following 2 papers provide you guidance on how to use the tool:
- https://academic.oup.com/nar/article/48/12/e72/5843822?login=false 
- https://www.nature.com/articles/s41596-022-00688-5
I would read them in this order, cause the Nature Protocols paper to some extend assumes prior knowledge.

As for ChimeraX, we don't have any tutorial. But there's loads of information available online.
You can open a PDB file constructed by taco oxDNA in just the same way you would open up a "protein" PDB
and change the render options according to your likings.
The thing you are looking for is the Molecule Display -> Surfaces tab. Additionally I strongly advise you to read the tutorials for ChimeraX if you are interested in using it.
